/* MTI_DPI */

/*
 * Copyright 2002-2014 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_XEX_AES256
#define INCLUDED_XEX_AES256

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
aes256_decrypt_ecb_file(
    const char* keyname,
    const char* inname,
    const char* outname);

DPI_LINK_DECL DPI_DLLESPEC
void
aes256_encrypt_ecb_file(
    const char* keyname,
    const char* inname,
    const char* outname);

DPI_LINK_DECL DPI_DLLESPEC
void
aes256_ks_file(
    const char* inname,
    const char* outname);

DPI_LINK_DECL DPI_DLLESPEC
void
xex_decrypt_file(
    const char* keyname,
    const char* inname,
    const char* outname);

DPI_LINK_DECL DPI_DLLESPEC
void
xex_doubleingf_file(
    const char* inname,
    const char* outname);

DPI_LINK_DECL DPI_DLLESPEC
void
xex_encrypt_file(
    const char* keyname,
    const char* inname,
    const char* outname);

#endif 
